### ISSUE TITLE
Disables PurePerms.

### ISSUE THREAD

**Issue by Dogeee** [TheDeibo/Colormatic#2]
Whenever I run this plugin, PurePerms immediately stops working.

**Comment by TheDeibo** [comment]
Not enough information. Need more information.  Also. please add some evidence, as I have tested this plugin, and it works.

**Comment by Dogeee** [comment]
Install the PurePerms and PureChat plugins from Poggit, then run Colourmatic then PureChat will be disabled.

**Comment by TheDeibo** [comment]
Do you get this error? `[Server thread/NOTICE]: [PureChat] No valid factions plugin in default-factions-plugin node was found. Disabling factions plugin support.`

**Comment by Dogeee** [comment]
No I don’t, this is an issue with this plugin since PurePerms worked fine earlier.

**Comment by TheDeibo** [comment]
I found the issue. 
in my code, I have added `$ev->setCancelled(true);`, so it doesn't disable the PureChat plugin, as that works perfectly. It simply cancelled out the chat event, and replaced with Colourmatic.

**Comment by Dogeee** [comment]
Thanks :D
